__name__ = "random-password-generator"
__name_desc__ = "Random Password Generator"
__version__ = "1.0.0"
__description__ = "Utility script to generate random entropic password"
__url__ = "https://github.com/Leovalcante/random-password-generator"
